apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user
  labels:
    app: udagram-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-user
  template:
    metadata:
      labels:
        app: udagram-user
    spec:
      containers:
        - name: udacity-cd-udagram-user
          image: fgil666/udacity-cd-udagram-user
          ports:
            - containerPort: 8080
